name: Deploy Node Applicatiom

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        run: docker build -t akhilpragallapati/nodejs-app .
      - name: Publish image to docker hub
        run: docker push akhilpragallapati/nodejs-app:latest

  delpoy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull akhilpragallapati/nodejs-app:latest
      - name: Delete old container if exists
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container akhilpragallapati/nodejs-app
      - name: outfile
        run: echo "run success full"

